-   repo: https://github.com/lagarciag/pre-commit-golang.git
    sha: e8b317f77908e4acd55dc192fdc5a776ba9877fe
    stages:
    - commit
    hooks:
    -   id: go-fmt
    -   id: go-lint
    -   id: go-vet 
    -   id: py-yapf
    -   id: go-check-tests
    -   id: go-codenanny
#    -   id: c-uncrustify

